from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon 
from PyQt5.QtCore import Qt
from juzedit import Ui_juzEditWindow, juzNumber_dictionary
import json
from roundProgressBar import QRoundProgressBar

# Reading in the Juz dictionary from JSON file
with open('data.json', 'r') as f:
    juz_data = json.load(f)

class Ui_interfaceWindow(object):
    def setupUi(self, interfaceWindow):

               
    # Qt Designer GUI Template                                            
        interfaceWindow.setObjectName("interfaceWindow")
        interfaceWindow.resize(1122, 885)
        font = QtGui.QFont()
        font.setPointSize(1)
        interfaceWindow.setFont(font)
        interfaceWindow.setSizeGripEnabled(False)
        interfaceWindow.setModal(False)
        self.buttonBox = QtWidgets.QDialogButtonBox(interfaceWindow)
        self.buttonBox.setGeometry(QtCore.QRect(890, 800, 156, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(interfaceWindow)
        self.label.setGeometry(QtCore.QRect(625, 130, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.scrollArea = QtWidgets.QScrollArea(interfaceWindow)
        self.scrollArea.setGeometry(QtCore.QRect(620, 160, 431, 631))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollArea.setLineWidth(5)
        self.scrollArea.setMidLineWidth(0)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 412, 997))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_34 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setIndent(-2)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_34.addWidget(self.label_34)
        self.juzOne_progressBar_2 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juzOne_progressBar_2.sizePolicy().hasHeightForWidth())
        self.juzOne_progressBar_2.setSizePolicy(sizePolicy)
        self.juzOne_progressBar_2.setMinimumSize(QtCore.QSize(0, 27))
        self.juzOne_progressBar_2.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.juzOne_progressBar_2.setFont(font)
        self.juzOne_progressBar_2.setOrientation(QtCore.Qt.Horizontal)
        self.juzOne_progressBar_2.setObjectName("juzOne_progressBar_2")
        self.horizontalLayout_34.addWidget(self.juzOne_progressBar_2)
        self.verticalLayout.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.label_43 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_43.sizePolicy().hasHeightForWidth())
        self.label_43.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setIndent(-2)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_43.addWidget(self.label_43)
        self.juzOne_progressBar_11 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juzOne_progressBar_11.sizePolicy().hasHeightForWidth())
        self.juzOne_progressBar_11.setSizePolicy(sizePolicy)
        self.juzOne_progressBar_11.setMinimumSize(QtCore.QSize(0, 27))
        self.juzOne_progressBar_11.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.juzOne_progressBar_11.setFont(font)
        self.juzOne_progressBar_11.setOrientation(QtCore.Qt.Horizontal)
        self.juzOne_progressBar_11.setObjectName("juzOne_progressBar_11")
        self.horizontalLayout_43.addWidget(self.juzOne_progressBar_11)
        self.verticalLayout.addLayout(self.horizontalLayout_43)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.label_42 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_42.sizePolicy().hasHeightForWidth())
        self.label_42.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setIndent(-2)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_42.addWidget(self.label_42)
        self.juzOne_progressBar_10 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juzOne_progressBar_10.sizePolicy().hasHeightForWidth())
        self.juzOne_progressBar_10.setSizePolicy(sizePolicy)
        self.juzOne_progressBar_10.setMinimumSize(QtCore.QSize(0, 27))
        self.juzOne_progressBar_10.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.juzOne_progressBar_10.setFont(font)
        self.juzOne_progressBar_10.setOrientation(QtCore.Qt.Horizontal)
        self.juzOne_progressBar_10.setObjectName("juzOne_progressBar_10")
        self.horizontalLayout_42.addWidget(self.juzOne_progressBar_10)
        self.verticalLayout.addLayout(self.horizontalLayout_42)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.label_40 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_40.sizePolicy().hasHeightForWidth())
        self.label_40.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setIndent(-2)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_40.addWidget(self.label_40)
        self.juzOne_progressBar_8 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juzOne_progressBar_8.sizePolicy().hasHeightForWidth())
        self.juzOne_progressBar_8.setSizePolicy(sizePolicy)
        self.juzOne_progressBar_8.setMinimumSize(QtCore.QSize(0, 27))
        self.juzOne_progressBar_8.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.juzOne_progressBar_8.setFont(font)
        self.juzOne_progressBar_8.setOrientation(QtCore.Qt.Horizontal)
        self.juzOne_progressBar_8.setObjectName("juzOne_progressBar_8")
        self.horizontalLayout_40.addWidget(self.juzOne_progressBar_8)
        self.verticalLayout.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_35 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_35.sizePolicy().hasHeightForWidth())
        self.label_35.setSizePolicy(sizePolicy)

        # Large Total Progress Bar
        # Initializes the overall progress bar as the average of the 30 juz percentage
        total = 0
        for value in juz_data.values():
            total += value
    
            average = total / 30
            average_int = int(average)


        # create the QRoundProgressBar and add it to the layout
        self.bar = QRoundProgressBar()
        self.bar.setFixedSize(400, 400)
        self.bar.setDataPenWidth(3)
        self.bar.setOutlinePenWidth(3)
        self.bar.setDonutThicknessRatio(0.85)
        self.bar.setDecimals(0)
        # self.bar.resetFormat()
        self.bar.setNullPosition(90)
        self.bar.setBarStyle(QRoundProgressBar.StyleDonut)
        self.bar.setDataColors([(0., QtGui.QColor.fromRgb(255,0,0)), (0.5, QtGui.QColor.fromRgb(255,255,0)), (1., QtGui.QColor.fromRgb(0,255,0))])
        self.bar.setValue(average_int)
        # set the central widget to the interfaceWindow
        lay = QtWidgets.QVBoxLayout(interfaceWindow)
        lay.addWidget(self.bar)
        horizontalLayoutWidget = QtWidgets.QWidget(interfaceWindow)
        horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        horizontalLayoutWidget.setGeometry(QtCore.QRect(99, 265, 451, 461))

        qprogressbarlayouthing = QtWidgets.QHBoxLayout(horizontalLayoutWidget)
        qprogressbarlayouthing.setObjectName("qprogressbarlayouthing")
        qprogressbarlayouthing.setContentsMargins(0, 0, 0, 0)
        qprogressbarlayouthing.addWidget(self.bar)

        label_3 = QtWidgets.QLabel(interfaceWindow)
        label_3.setObjectName("label_3")
        label_3.setGeometry(QtCore.QRect(170, 60, 321, 141))
        label_3.setStyleSheet("background-image: url(C:/Users/noobd/OneDrive/Documents/GitHub/QuranReviser/src/titleIcon.png)")
        label_3.setPixmap(QtGui.QPixmap("C:/Users/noobd/OneDrive/Documents/GitHub/QuranReviser/src/titleIcon.png"))
        label_3.setScaledContents(True)


        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setIndent(-2)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_35.addWidget(self.label_35)
        self.juzOne_progressBar_3 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juzOne_progressBar_3.sizePolicy().hasHeightForWidth())
        self.juzOne_progressBar_3.setSizePolicy(sizePolicy)
        self.juzOne_progressBar_3.setMinimumSize(QtCore.QSize(0, 27))
        self.juzOne_progressBar_3.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.juzOne_progressBar_3.setFont(font)
        self.juzOne_progressBar_3.setOrientation(QtCore.Qt.Horizontal)
        self.juzOne_progressBar_3.setObjectName("juzOne_progressBar_3")
        self.horizontalLayout_35.addWidget(self.juzOne_progressBar_3)
        self.verticalLayout.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.label_41 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_41.sizePolicy().hasHeightForWidth())
        self.label_41.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setIndent(-2)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_41.addWidget(self.label_41)
        self.juzOne_progressBar_9 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juzOne_progressBar_9.sizePolicy().hasHeightForWidth())
        self.juzOne_progressBar_9.setSizePolicy(sizePolicy)
        self.juzOne_progressBar_9.setMinimumSize(QtCore.QSize(0, 27))
        self.juzOne_progressBar_9.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.juzOne_progressBar_9.setFont(font)
        self.juzOne_progressBar_9.setOrientation(QtCore.Qt.Horizontal)
        self.juzOne_progressBar_9.setObjectName("juzOne_progressBar_9")
        self.horizontalLayout_41.addWidget(self.juzOne_progressBar_9)
        self.verticalLayout.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_38 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setIndent(-2)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_38.addWidget(self.label_38)
        self.juzOne_progressBar_6 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juzOne_progressBar_6.sizePolicy().hasHeightForWidth())
        self.juzOne_progressBar_6.setSizePolicy(sizePolicy)
        self.juzOne_progressBar_6.setMinimumSize(QtCore.QSize(0, 27))
        self.juzOne_progressBar_6.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.juzOne_progressBar_6.setFont(font)
        self.juzOne_progressBar_6.setOrientation(QtCore.Qt.Horizontal)
        self.juzOne_progressBar_6.setObjectName("juzOne_progressBar_6")
        self.horizontalLayout_38.addWidget(self.juzOne_progressBar_6)
        self.verticalLayout.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.label_44 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setIndent(-2)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_44.addWidget(self.label_44)
        self.juzOne_progressBar_12 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juzOne_progressBar_12.sizePolicy().hasHeightForWidth())
        self.juzOne_progressBar_12.setSizePolicy(sizePolicy)
        self.juzOne_progressBar_12.setMinimumSize(QtCore.QSize(0, 27))
        self.juzOne_progressBar_12.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.juzOne_progressBar_12.setFont(font)
        self.juzOne_progressBar_12.setOrientation(QtCore.Qt.Horizontal)
        self.juzOne_progressBar_12.setObjectName("juzOne_progressBar_12")
        self.horizontalLayout_44.addWidget(self.juzOne_progressBar_12)
        self.verticalLayout.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_36 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setIndent(-2)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_36.addWidget(self.label_36)
        self.juzOne_progressBar_4 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juzOne_progressBar_4.sizePolicy().hasHeightForWidth())
        self.juzOne_progressBar_4.setSizePolicy(sizePolicy)
        self.juzOne_progressBar_4.setMinimumSize(QtCore.QSize(0, 27))
        self.juzOne_progressBar_4.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.juzOne_progressBar_4.setFont(font)
        self.juzOne_progressBar_4.setOrientation(QtCore.Qt.Horizontal)
        self.juzOne_progressBar_4.setObjectName("juzOne_progressBar_4")
        self.horizontalLayout_36.addWidget(self.juzOne_progressBar_4)
        self.verticalLayout.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_37 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setIndent(-2)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_37.addWidget(self.label_37)
        self.juzOne_progressBar_5 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juzOne_progressBar_5.sizePolicy().hasHeightForWidth())
        self.juzOne_progressBar_5.setSizePolicy(sizePolicy)
        self.juzOne_progressBar_5.setMinimumSize(QtCore.QSize(0, 27))
        self.juzOne_progressBar_5.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.juzOne_progressBar_5.setFont(font)
        self.juzOne_progressBar_5.setOrientation(QtCore.Qt.Horizontal)
        self.juzOne_progressBar_5.setObjectName("juzOne_progressBar_5")
        self.horizontalLayout_37.addWidget(self.juzOne_progressBar_5)
        self.verticalLayout.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_39 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_39.sizePolicy().hasHeightForWidth())
        self.label_39.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setIndent(-2)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_39.addWidget(self.label_39)
        self.juzOne_progressBar_7 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juzOne_progressBar_7.sizePolicy().hasHeightForWidth())
        self.juzOne_progressBar_7.setSizePolicy(sizePolicy)
        self.juzOne_progressBar_7.setMinimumSize(QtCore.QSize(0, 27))
        self.juzOne_progressBar_7.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.juzOne_progressBar_7.setFont(font)
        self.juzOne_progressBar_7.setOrientation(QtCore.Qt.Horizontal)
        self.juzOne_progressBar_7.setObjectName("juzOne_progressBar_7")
        self.horizontalLayout_39.addWidget(self.juzOne_progressBar_7)
        self.verticalLayout.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setIndent(-2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.juzOne_progressBar = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juzOne_progressBar.sizePolicy().hasHeightForWidth())
        self.juzOne_progressBar.setSizePolicy(sizePolicy)
        self.juzOne_progressBar.setMinimumSize(QtCore.QSize(0, 27))
        self.juzOne_progressBar.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.juzOne_progressBar.setFont(font)
        self.juzOne_progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.juzOne_progressBar.setObjectName("juzOne_progressBar")
        self.horizontalLayout_2.addWidget(self.juzOne_progressBar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.label_45 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_45.sizePolicy().hasHeightForWidth())
        self.label_45.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setIndent(-2)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_45.addWidget(self.label_45)
        self.juzOne_progressBar_13 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juzOne_progressBar_13.sizePolicy().hasHeightForWidth())
        self.juzOne_progressBar_13.setSizePolicy(sizePolicy)
        self.juzOne_progressBar_13.setMinimumSize(QtCore.QSize(0, 27))
        self.juzOne_progressBar_13.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.juzOne_progressBar_13.setFont(font)
        self.juzOne_progressBar_13.setOrientation(QtCore.Qt.Horizontal)
        self.juzOne_progressBar_13.setObjectName("juzOne_progressBar_13")
        self.horizontalLayout_45.addWidget(self.juzOne_progressBar_13)
        self.verticalLayout.addLayout(self.horizontalLayout_45)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.label_46 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_46.sizePolicy().hasHeightForWidth())
        self.label_46.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setIndent(-2)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_46.addWidget(self.label_46)
        self.juzOne_progressBar_14 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juzOne_progressBar_14.sizePolicy().hasHeightForWidth())
        self.juzOne_progressBar_14.setSizePolicy(sizePolicy)
        self.juzOne_progressBar_14.setMinimumSize(QtCore.QSize(0, 27))
        self.juzOne_progressBar_14.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.juzOne_progressBar_14.setFont(font)
        self.juzOne_progressBar_14.setOrientation(QtCore.Qt.Horizontal)
        self.juzOne_progressBar_14.setObjectName("juzOne_progressBar_14")
        self.horizontalLayout_46.addWidget(self.juzOne_progressBar_14)
        self.verticalLayout.addLayout(self.horizontalLayout_46)
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.label_47 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_47.sizePolicy().hasHeightForWidth())
        self.label_47.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setIndent(-2)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_47.addWidget(self.label_47)
        self.juzOne_progressBar_15 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juzOne_progressBar_15.sizePolicy().hasHeightForWidth())
        self.juzOne_progressBar_15.setSizePolicy(sizePolicy)
        self.juzOne_progressBar_15.setMinimumSize(QtCore.QSize(0, 27))
        self.juzOne_progressBar_15.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.juzOne_progressBar_15.setFont(font)
        self.juzOne_progressBar_15.setOrientation(QtCore.Qt.Horizontal)
        self.juzOne_progressBar_15.setObjectName("juzOne_progressBar_15")
        self.horizontalLayout_47.addWidget(self.juzOne_progressBar_15)
        self.verticalLayout.addLayout(self.horizontalLayout_47)
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_48.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.label_48 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_48.sizePolicy().hasHeightForWidth())
        self.label_48.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setIndent(-2)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_48.addWidget(self.label_48)
        self.juzOne_progressBar_16 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juzOne_progressBar_16.sizePolicy().hasHeightForWidth())
        self.juzOne_progressBar_16.setSizePolicy(sizePolicy)
        self.juzOne_progressBar_16.setMinimumSize(QtCore.QSize(0, 27))
        self.juzOne_progressBar_16.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.juzOne_progressBar_16.setFont(font)
        self.juzOne_progressBar_16.setOrientation(QtCore.Qt.Horizontal)
        self.juzOne_progressBar_16.setObjectName("juzOne_progressBar_16")
        self.horizontalLayout_48.addWidget(self.juzOne_progressBar_16)
        self.verticalLayout.addLayout(self.horizontalLayout_48)
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.label_50 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_50.sizePolicy().hasHeightForWidth())
        self.label_50.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setIndent(-2)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_50.addWidget(self.label_50)
        self.juzOne_progressBar_18 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juzOne_progressBar_18.sizePolicy().hasHeightForWidth())
        self.juzOne_progressBar_18.setSizePolicy(sizePolicy)
        self.juzOne_progressBar_18.setMinimumSize(QtCore.QSize(0, 27))
        self.juzOne_progressBar_18.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.juzOne_progressBar_18.setFont(font)
        self.juzOne_progressBar_18.setOrientation(QtCore.Qt.Horizontal)
        self.juzOne_progressBar_18.setObjectName("juzOne_progressBar_18")
        self.horizontalLayout_50.addWidget(self.juzOne_progressBar_18)
        self.verticalLayout.addLayout(self.horizontalLayout_50)
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.label_49 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_49.sizePolicy().hasHeightForWidth())
        self.label_49.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setIndent(-2)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_49.addWidget(self.label_49)
        self.juzOne_progressBar_17 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juzOne_progressBar_17.sizePolicy().hasHeightForWidth())
        self.juzOne_progressBar_17.setSizePolicy(sizePolicy)
        self.juzOne_progressBar_17.setMinimumSize(QtCore.QSize(0, 27))
        self.juzOne_progressBar_17.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.juzOne_progressBar_17.setFont(font)
        self.juzOne_progressBar_17.setOrientation(QtCore.Qt.Horizontal)
        self.juzOne_progressBar_17.setObjectName("juzOne_progressBar_17")
        self.horizontalLayout_49.addWidget(self.juzOne_progressBar_17)
        self.verticalLayout.addLayout(self.horizontalLayout_49)
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_53.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        self.label_53 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_53.sizePolicy().hasHeightForWidth())
        self.label_53.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setIndent(-2)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_53.addWidget(self.label_53)
        self.juzOne_progressBar_21 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juzOne_progressBar_21.sizePolicy().hasHeightForWidth())
        self.juzOne_progressBar_21.setSizePolicy(sizePolicy)
        self.juzOne_progressBar_21.setMinimumSize(QtCore.QSize(0, 27))
        self.juzOne_progressBar_21.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.juzOne_progressBar_21.setFont(font)
        self.juzOne_progressBar_21.setOrientation(QtCore.Qt.Horizontal)
        self.juzOne_progressBar_21.setObjectName("juzOne_progressBar_21")
        self.horizontalLayout_53.addWidget(self.juzOne_progressBar_21)
        self.verticalLayout.addLayout(self.horizontalLayout_53)
        self.horizontalLayout_59 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_59.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        self.label_59 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_59.sizePolicy().hasHeightForWidth())
        self.label_59.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setIndent(-2)
        self.label_59.setObjectName("label_59")
        self.horizontalLayout_59.addWidget(self.label_59)
        self.juzOne_progressBar_27 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juzOne_progressBar_27.sizePolicy().hasHeightForWidth())
        self.juzOne_progressBar_27.setSizePolicy(sizePolicy)
        self.juzOne_progressBar_27.setMinimumSize(QtCore.QSize(0, 27))
        self.juzOne_progressBar_27.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.juzOne_progressBar_27.setFont(font)
        self.juzOne_progressBar_27.setOrientation(QtCore.Qt.Horizontal)
        self.juzOne_progressBar_27.setObjectName("juzOne_progressBar_27")
        self.horizontalLayout_59.addWidget(self.juzOne_progressBar_27)
        self.verticalLayout.addLayout(self.horizontalLayout_59)
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.label_51 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_51.sizePolicy().hasHeightForWidth())
        self.label_51.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setIndent(-2)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_51.addWidget(self.label_51)
        self.juzOne_progressBar_19 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juzOne_progressBar_19.sizePolicy().hasHeightForWidth())
        self.juzOne_progressBar_19.setSizePolicy(sizePolicy)
        self.juzOne_progressBar_19.setMinimumSize(QtCore.QSize(0, 27))
        self.juzOne_progressBar_19.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.juzOne_progressBar_19.setFont(font)
        self.juzOne_progressBar_19.setOrientation(QtCore.Qt.Horizontal)
        self.juzOne_progressBar_19.setObjectName("juzOne_progressBar_19")
        self.horizontalLayout_51.addWidget(self.juzOne_progressBar_19)
        self.verticalLayout.addLayout(self.horizontalLayout_51)
        self.horizontalLayout_55 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_55.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_55.setObjectName("horizontalLayout_55")
        self.label_55 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_55.sizePolicy().hasHeightForWidth())
        self.label_55.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setIndent(-2)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_55.addWidget(self.label_55)
        self.juzOne_progressBar_23 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juzOne_progressBar_23.sizePolicy().hasHeightForWidth())
        self.juzOne_progressBar_23.setSizePolicy(sizePolicy)
        self.juzOne_progressBar_23.setMinimumSize(QtCore.QSize(0, 27))
        self.juzOne_progressBar_23.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.juzOne_progressBar_23.setFont(font)
        self.juzOne_progressBar_23.setOrientation(QtCore.Qt.Horizontal)
        self.juzOne_progressBar_23.setObjectName("juzOne_progressBar_23")
        self.horizontalLayout_55.addWidget(self.juzOne_progressBar_23)
        self.verticalLayout.addLayout(self.horizontalLayout_55)
        self.horizontalLayout_54 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_54.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_54.setObjectName("horizontalLayout_54")
        self.label_54 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_54.sizePolicy().hasHeightForWidth())
        self.label_54.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setIndent(-2)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_54.addWidget(self.label_54)
        self.juzOne_progressBar_22 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juzOne_progressBar_22.sizePolicy().hasHeightForWidth())
        self.juzOne_progressBar_22.setSizePolicy(sizePolicy)
        self.juzOne_progressBar_22.setMinimumSize(QtCore.QSize(0, 27))
        self.juzOne_progressBar_22.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.juzOne_progressBar_22.setFont(font)
        self.juzOne_progressBar_22.setOrientation(QtCore.Qt.Horizontal)
        self.juzOne_progressBar_22.setObjectName("juzOne_progressBar_22")
        self.horizontalLayout_54.addWidget(self.juzOne_progressBar_22)
        self.verticalLayout.addLayout(self.horizontalLayout_54)
        self.horizontalLayout_56 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_56.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_56.setObjectName("horizontalLayout_56")
        self.label_56 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_56.sizePolicy().hasHeightForWidth())
        self.label_56.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setIndent(-2)
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_56.addWidget(self.label_56)
        self.juzOne_progressBar_24 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juzOne_progressBar_24.sizePolicy().hasHeightForWidth())
        self.juzOne_progressBar_24.setSizePolicy(sizePolicy)
        self.juzOne_progressBar_24.setMinimumSize(QtCore.QSize(0, 27))
        self.juzOne_progressBar_24.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.juzOne_progressBar_24.setFont(font)
        self.juzOne_progressBar_24.setOrientation(QtCore.Qt.Horizontal)
        self.juzOne_progressBar_24.setObjectName("juzOne_progressBar_24")
        self.horizontalLayout_56.addWidget(self.juzOne_progressBar_24)
        self.verticalLayout.addLayout(self.horizontalLayout_56)
        self.horizontalLayout_58 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_58.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_58.setObjectName("horizontalLayout_58")
        self.label_58 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_58.sizePolicy().hasHeightForWidth())
        self.label_58.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_58.setFont(font)
        self.label_58.setIndent(-2)
        self.label_58.setObjectName("label_58")
        self.horizontalLayout_58.addWidget(self.label_58)
        self.juzOne_progressBar_26 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juzOne_progressBar_26.sizePolicy().hasHeightForWidth())
        self.juzOne_progressBar_26.setSizePolicy(sizePolicy)
        self.juzOne_progressBar_26.setMinimumSize(QtCore.QSize(0, 27))
        self.juzOne_progressBar_26.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.juzOne_progressBar_26.setFont(font)
        self.juzOne_progressBar_26.setOrientation(QtCore.Qt.Horizontal)
        self.juzOne_progressBar_26.setObjectName("juzOne_progressBar_26")
        self.horizontalLayout_58.addWidget(self.juzOne_progressBar_26)
        self.verticalLayout.addLayout(self.horizontalLayout_58)
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_57.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.label_57 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_57.sizePolicy().hasHeightForWidth())
        self.label_57.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setIndent(-2)
        self.label_57.setObjectName("label_57")
        self.horizontalLayout_57.addWidget(self.label_57)
        self.juzOne_progressBar_25 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juzOne_progressBar_25.sizePolicy().hasHeightForWidth())
        self.juzOne_progressBar_25.setSizePolicy(sizePolicy)
        self.juzOne_progressBar_25.setMinimumSize(QtCore.QSize(0, 27))
        self.juzOne_progressBar_25.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.juzOne_progressBar_25.setFont(font)
        self.juzOne_progressBar_25.setOrientation(QtCore.Qt.Horizontal)
        self.juzOne_progressBar_25.setObjectName("juzOne_progressBar_25")
        self.horizontalLayout_57.addWidget(self.juzOne_progressBar_25)
        self.verticalLayout.addLayout(self.horizontalLayout_57)
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_52.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.label_52 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_52.sizePolicy().hasHeightForWidth())
        self.label_52.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setIndent(-2)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_52.addWidget(self.label_52)
        self.juzOne_progressBar_20 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juzOne_progressBar_20.sizePolicy().hasHeightForWidth())
        self.juzOne_progressBar_20.setSizePolicy(sizePolicy)
        self.juzOne_progressBar_20.setMinimumSize(QtCore.QSize(0, 27))
        self.juzOne_progressBar_20.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.juzOne_progressBar_20.setFont(font)
        self.juzOne_progressBar_20.setOrientation(QtCore.Qt.Horizontal)
        self.juzOne_progressBar_20.setObjectName("juzOne_progressBar_20")
        self.horizontalLayout_52.addWidget(self.juzOne_progressBar_20)
        self.verticalLayout.addLayout(self.horizontalLayout_52)
        self.horizontalLayout_60 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_60.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_60.setObjectName("horizontalLayout_60")
        self.label_60 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_60.sizePolicy().hasHeightForWidth())
        self.label_60.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_60.setFont(font)
        self.label_60.setIndent(-2)
        self.label_60.setObjectName("label_60")
        self.horizontalLayout_60.addWidget(self.label_60)
        self.juzOne_progressBar_28 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juzOne_progressBar_28.sizePolicy().hasHeightForWidth())
        self.juzOne_progressBar_28.setSizePolicy(sizePolicy)
        self.juzOne_progressBar_28.setMinimumSize(QtCore.QSize(0, 27))
        self.juzOne_progressBar_28.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.juzOne_progressBar_28.setFont(font)
        self.juzOne_progressBar_28.setOrientation(QtCore.Qt.Horizontal)
        self.juzOne_progressBar_28.setObjectName("juzOne_progressBar_28")
        self.horizontalLayout_60.addWidget(self.juzOne_progressBar_28)
        self.verticalLayout.addLayout(self.horizontalLayout_60)
        self.horizontalLayout_61 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_61.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_61.setObjectName("horizontalLayout_61")
        self.label_61 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_61.sizePolicy().hasHeightForWidth())
        self.label_61.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_61.setFont(font)
        self.label_61.setIndent(-2)
        self.label_61.setObjectName("label_61")
        self.horizontalLayout_61.addWidget(self.label_61)
        self.juzOne_progressBar_29 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juzOne_progressBar_29.sizePolicy().hasHeightForWidth())
        self.juzOne_progressBar_29.setSizePolicy(sizePolicy)
        self.juzOne_progressBar_29.setMinimumSize(QtCore.QSize(0, 27))
        self.juzOne_progressBar_29.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.juzOne_progressBar_29.setFont(font)
        self.juzOne_progressBar_29.setOrientation(QtCore.Qt.Horizontal)
        self.juzOne_progressBar_29.setObjectName("juzOne_progressBar_29")
        self.horizontalLayout_61.addWidget(self.juzOne_progressBar_29)
        self.verticalLayout.addLayout(self.horizontalLayout_61)
        self.horizontalLayout_62 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_62.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_62.setObjectName("horizontalLayout_62")
        self.label_62 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_62.sizePolicy().hasHeightForWidth())
        self.label_62.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_62.setFont(font)
        self.label_62.setIndent(-2)
        self.label_62.setObjectName("label_62")
        self.horizontalLayout_62.addWidget(self.label_62)
        self.juzOne_progressBar_30 = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.juzOne_progressBar_30.sizePolicy().hasHeightForWidth())
        self.juzOne_progressBar_30.setSizePolicy(sizePolicy)
        self.juzOne_progressBar_30.setMinimumSize(QtCore.QSize(0, 27))
        self.juzOne_progressBar_30.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.juzOne_progressBar_30.setFont(font)
        self.juzOne_progressBar_30.setOrientation(QtCore.Qt.Horizontal)
        self.juzOne_progressBar_30.setObjectName("juzOne_progressBar_30")
        self.horizontalLayout_62.addWidget(self.juzOne_progressBar_30)
        self.verticalLayout.addLayout(self.horizontalLayout_62)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButton = QtWidgets.QPushButton(interfaceWindow, clicked = lambda: self.openJuzEditor())
        self.pushButton.setGeometry(QtCore.QRect(730, 130, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(interfaceWindow)
        self.pushButton_2.setGeometry(QtCore.QRect(820, 130, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.update_juz_percentages)
        self.pushButton_2.clicked.connect(self.update_averages)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_64 = QtWidgets.QLabel(interfaceWindow)
        self.label_64.setGeometry(QtCore.QRect(200, 40, 731, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_64.setFont(font)
        self.label_64.setObjectName("label_64")
        self.actiontest = QtWidgets.QAction(interfaceWindow)
        self.actiontest.setObjectName("actiontest")
        # end of Qt Designer GUI Template

        # Changing colors of percentage bars, based on the percentage value it holds
        def set_progress_bar_color(progress_bar, progress_percent):
                if progress_percent == 75:
                    progress_bar.setStyleSheet("QProgressBar::chunk { background-color: yellow; }")
                elif progress_percent == 50:
                    progress_bar.setStyleSheet("QProgressBar::chunk { background-color: red; }")
                else:
                    progress_bar.setStyleSheet("")


        # Initializing all of the progress bars percentages to the values from JSON file
        # variable names suck, my bad : ) - note: variable names MATTER
        for juz, value in juz_data.items():
            if juz == "Juz 1":
                self.juzOne_progressBar_2.setValue(value)
            elif juz == "Juz 2":
                self.juzOne_progressBar_11.setValue(value)
            elif juz == "Juz 3":
                self.juzOne_progressBar_10.setValue(value)
            elif juz == "Juz 4":
                self.juzOne_progressBar_8.setValue(value)
            elif juz == "Juz 5":
                self.juzOne_progressBar_3.setValue(value)
            elif juz == "Juz 6":
                self.juzOne_progressBar_9.setValue(value)
            elif juz == "Juz 7":
                self.juzOne_progressBar_6.setValue(value)
            elif juz == "Juz 8":
                self.juzOne_progressBar_12.setValue(value)
            elif juz == "Juz 9":
                self.juzOne_progressBar_4.setValue(value)
            elif juz == "Juz 10":
                self.juzOne_progressBar_5.setValue(value)
            elif juz == "Juz 11":
                self.juzOne_progressBar_7.setValue(value)
            elif juz == "Juz 12":
                self.juzOne_progressBar.setValue(value)
            elif juz == "Juz 13":
                self.juzOne_progressBar_13.setValue(value)
            elif juz == "Juz 14":
                self.juzOne_progressBar_14.setValue(value)
            elif juz == "Juz 15":
                self.juzOne_progressBar_15.setValue(value)
            elif juz == "Juz 16":
                self.juzOne_progressBar_16.setValue(value)
            elif juz == "Juz 17":
                self.juzOne_progressBar_18.setValue(value)
            elif juz == "Juz 18":
                self.juzOne_progressBar_17.setValue(value)
            elif juz == "Juz 19":
                self.juzOne_progressBar_21.setValue(value)
            elif juz == "Juz 20":
                self.juzOne_progressBar_27.setValue(value)
            elif juz == "Juz 21":
                self.juzOne_progressBar_19.setValue(value)
            elif juz == "Juz 22":
                self.juzOne_progressBar_23.setValue(value)
            elif juz == "Juz 23":
                self.juzOne_progressBar_22.setValue(value)
            elif juz == "Juz 24":
                self.juzOne_progressBar_24.setValue(value)
            elif juz == "Juz 25":
                self.juzOne_progressBar_26.setValue(value)
            elif juz == "Juz 26":
                self.juzOne_progressBar_25.setValue(value)
            elif juz == "Juz 27":
                self.juzOne_progressBar_20.setValue(value)
            elif juz == "Juz 28":
                self.juzOne_progressBar_28.setValue(value)
            elif juz == "Juz 29":
                self.juzOne_progressBar_29.setValue(value)
            elif juz == "Juz 30":
                self.juzOne_progressBar_30.setValue(value)

        self.retranslateUi(interfaceWindow)
        self.buttonBox.accepted.connect(interfaceWindow.accept) # type: ignore
        self.buttonBox.rejected.connect(interfaceWindow.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(interfaceWindow)

        # Added the icon and top right window min, max, and close
        icon = QIcon('C:/Users/noobd/Documents/GitHub/QuranReviser/src/quranIcon.PNG')
        interfaceWindow.setWindowIcon(icon) # icon top left
        interfaceWindow.setWindowTitle('QuranRevisor') # name of the window
        interfaceWindow.setWindowFlags(Qt.Window | Qt.WindowMinimizeButtonHint | Qt.WindowCloseButtonHint)

    # Qt Designer GUI Template - juz names and labels
    def retranslateUi(self, interfaceWindow):
        _translate = QtCore.QCoreApplication.translate
        interfaceWindow.setWindowTitle(_translate("interfaceWindow", "Dialog"))
        self.label.setText(_translate("interfaceWindow", "Juz Editor :"))
        self.label_34.setText(_translate("interfaceWindow", "Juz 01"))
        self.label_43.setText(_translate("interfaceWindow", "Juz 02"))
        self.label_42.setText(_translate("interfaceWindow", "Juz 03"))
        self.label_40.setText(_translate("interfaceWindow", "Juz 04"))
        self.label_35.setText(_translate("interfaceWindow", "Juz 05"))
        self.label_41.setText(_translate("interfaceWindow", "Juz 06"))
        self.label_38.setText(_translate("interfaceWindow", "Juz 07"))
        self.label_44.setText(_translate("interfaceWindow", "Juz 08"))
        self.label_36.setText(_translate("interfaceWindow", "Juz 09"))
        self.label_37.setText(_translate("interfaceWindow", "Juz 10"))
        self.label_39.setText(_translate("interfaceWindow", "Juz 11"))
        self.label_2.setText(_translate("interfaceWindow", "Juz 12"))
        self.label_45.setText(_translate("interfaceWindow", "Juz 13"))
        self.label_46.setText(_translate("interfaceWindow", "Juz 14"))
        self.label_47.setText(_translate("interfaceWindow", "Juz 15"))
        self.label_48.setText(_translate("interfaceWindow", "Juz 16"))
        self.label_50.setText(_translate("interfaceWindow", "Juz 17"))
        self.label_49.setText(_translate("interfaceWindow", "Juz 18"))
        self.label_53.setText(_translate("interfaceWindow", "Juz 19"))
        self.label_59.setText(_translate("interfaceWindow", "Juz 20"))
        self.label_51.setText(_translate("interfaceWindow", "Juz 21"))
        self.label_55.setText(_translate("interfaceWindow", "Juz 22"))
        self.label_54.setText(_translate("interfaceWindow", "Juz 23"))
        self.label_56.setText(_translate("interfaceWindow", "Juz 24"))
        self.label_58.setText(_translate("interfaceWindow", "Juz 25"))
        self.label_57.setText(_translate("interfaceWindow", "Juz 26"))
        self.label_52.setText(_translate("interfaceWindow", "Juz 27"))
        self.label_60.setText(_translate("interfaceWindow", "Juz 28"))
        self.label_61.setText(_translate("interfaceWindow", "Juz 29"))
        self.label_62.setText(_translate("interfaceWindow", "Juz 30"))
        self.pushButton.setText(_translate("interfaceWindow", "Edit Juz"))
        self.pushButton_2.setText(_translate("interfaceWindow", "Update"))
       # self.label_64.setText(_translate("interfaceWindow", "Hifz Progress Tracker (tentative name)"))
        self.actiontest.setText(_translate("interfaceWindow", "test"))

    # Function opens Juz Editor when user clicks 'Edit Juz' button
    def openJuzEditor(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_juzEditWindow()
        self.ui.setupUi(self.window)
        self.window.show()
    
    # Function updates the Juz Percentages for each progress bar, user must click 'Update' for progress bars to change
    def update_juz_percentages(self):
        self.juzOne_progressBar_2.setValue(juzNumber_dictionary["Juz 1"])
        self.juzOne_progressBar_11.setValue(juzNumber_dictionary["Juz 2"])
        self.juzOne_progressBar_10.setValue(juzNumber_dictionary["Juz 3"])
        self.juzOne_progressBar_8.setValue(juzNumber_dictionary["Juz 4"])
        self.juzOne_progressBar_3.setValue(juzNumber_dictionary["Juz 5"])
        self.juzOne_progressBar_9.setValue(juzNumber_dictionary["Juz 6"])
        self.juzOne_progressBar_6.setValue(juzNumber_dictionary["Juz 7"])
        self.juzOne_progressBar_12.setValue(juzNumber_dictionary["Juz 8"])
        self.juzOne_progressBar_4.setValue(juzNumber_dictionary["Juz 9"])
        self.juzOne_progressBar_5.setValue(juzNumber_dictionary["Juz 10"])
        self.juzOne_progressBar_7.setValue(juzNumber_dictionary["Juz 11"])
        self.juzOne_progressBar.setValue(juzNumber_dictionary["Juz 12"])
        self.juzOne_progressBar_13.setValue(juzNumber_dictionary["Juz 13"])
        self.juzOne_progressBar_14.setValue(juzNumber_dictionary["Juz 14"])
        self.juzOne_progressBar_15.setValue(juzNumber_dictionary["Juz 15"])
        self.juzOne_progressBar_16.setValue(juzNumber_dictionary["Juz 16"])
        self.juzOne_progressBar_18.setValue(juzNumber_dictionary["Juz 17"])
        self.juzOne_progressBar_17.setValue(juzNumber_dictionary["Juz 18"])
        self.juzOne_progressBar_21.setValue(juzNumber_dictionary["Juz 19"])
        self.juzOne_progressBar_27.setValue(juzNumber_dictionary["Juz 20"])
        self.juzOne_progressBar_19.setValue(juzNumber_dictionary["Juz 21"])
        self.juzOne_progressBar_23.setValue(juzNumber_dictionary["Juz 22"])
        self.juzOne_progressBar_22.setValue(juzNumber_dictionary["Juz 23"])
        self.juzOne_progressBar_24.setValue(juzNumber_dictionary["Juz 24"])
        self.juzOne_progressBar_26.setValue(juzNumber_dictionary["Juz 25"])
        self.juzOne_progressBar_25.setValue(juzNumber_dictionary["Juz 26"])
        self.juzOne_progressBar_20.setValue(juzNumber_dictionary["Juz 27"])
        self.juzOne_progressBar_28.setValue(juzNumber_dictionary["Juz 28"])
        self.juzOne_progressBar_29.setValue(juzNumber_dictionary["Juz 29"])
        self.juzOne_progressBar_30.setValue(juzNumber_dictionary["Juz 30"])

    # Updates the average bar, by recomputing the average from the updates values in the dictionary
    # 'Update' button will update the main progress bar and all the other progress bars
    def update_averages(self):
        total = sum(juzNumber_dictionary.values())
        average = total / 30
        average_int = int(average)

        # Update the average progress bar value
        self.bar.setValue(average_int)
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    interfaceWindow = QtWidgets.QDialog()
    ui = Ui_interfaceWindow()
    ui.setupUi(interfaceWindow)
    interfaceWindow.show()
    sys.exit(app.exec_())
